
enum SystemType {
	FIRSTCHARGE = 1,
	ACTIVITY = 2,
	RANK = 3,
	MALL = 4,
	FULI = 5,
	MONTHCARD = 6,
	TREASURE = 7,
	WORLDMAP = 8,
	RING = 9,
	MIJI = 10,
	BOSS = 11,
	FB = 12,
	ONEKEY = 13,
	CHALLENGE = 14,
	SHENQIGUIDE = 15,
	BOOK = 16,
	WEAPONS = 17,
	GUILD = 18,//仙盟
	VIPGIFT = 19,//vip礼包
	LIMITTASK = 20,//限时任务
	FOCUS = 21,//关注
	SHARE = 22,//分享
	FENGCE = 23,//封测
	DAILYGIFT = 24,//每日礼包
	QUICKDROP = 25,//快速捡道具
	MABI = 26,//晕眩icon
	NEWEQUIP = 27,//新装备穿戴提示
	CITYMONSTER = 28,//怪物攻城
	DOUBLEELEVEN = 29, //双十一活动
	GODWEAPON = 30,//神兵
	SUPERVIP = 31,//超级会员
	CITY = 32,//主城
	THANKS = 33, //感恩节活动
	HFACTIVITY = 34, //合服活动
	DOUBLE_TWELVE = 35, //双12活动
	DOUBLE_TWELVE_RECHARGE = 36, //双12充值
	BATTLE = 37, //阵营战
	PAODIAN = 38, //瑶池盛会
	FESTIVAL = 39,//春节
	HUANSHOU = 40,//幻兽
	HAPPYSEVENDAY = 41,//七天乐
	EXTREME_EQUIP = 44,//至尊装备
	AWAKE_TASK = 45,//唤醒功能
	COLLECTGIFT = 46, //收藏有礼
	ZHANLING = 47,//天仙活动
	HEARTMETGOD = 48,//心法
	SPRINGFESTIVAL = 49,//春节活动
	SPRINGEIGHTDAY = 50,//春节8天活动
}